1. Create an array of 6 zeros 

In [54]:
import numpy as np
data=np.zeros((6),dtype=np.int16)
print(data)

[0 0 0 0 0 0]


2. Create an array of 6 ones

In [55]:
data=np.ones((6),dtype=np.int16)
print(data)

[1 1 1 1 1 1]


3.Create an array of 6 fives 

In [56]:
np.full((6),5)

array([5, 5, 5, 5, 5, 5])

4. Create an array of integers from 1 to 99 

In [57]:
np.arange(1,100,1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

5. Create an array of all the odd integers ranging from 1 to 99 

In [58]:
np.arange(1,100,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

6. Create a 2X2 matrix filled with values from 1 to 4 

In [59]:
np.array([(1,2),(3,4)])

array([[1, 2],
       [3, 4]])

7. Create a 3X3 matrix filled with values from 9 to 17 

In [60]:
matrix_3x3 = np.arange(9, 18).reshape(3, 3)

8. Make an indentity matrix of 4X4 

In [61]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

9. With the help of NumPy generate a random nos in between 0 to 1 

In [62]:
print(np.random.random((1,1)))

[[0.31798318]]


10. Compare two 3d array and display the results in terms of true and false 

In [63]:
a=np.array([[(1,2,3),(4,5,6)],[(7,8,9),(10,11,12)]])
b=np.array([[(2,2,2),(4,4,4)],[(9,9,9),(11,11,12)]])
print(np.array_equal(a,b))

False


11. Create a null vector of size 20 where the 6th value should be 0 

In [64]:
null_vector = np.zeros(20)
null_vector[5] = 1

12. Reverse an array of size 100 using numpy. 

In [65]:
reversed_array = np.arange(100)[::-1]

13. Find the minimum and maximum values of a 20X20 array using numpy 

In [66]:
array_20x20 = np.random.randint(0, 100, (20, 20))
min_value = array_20x20.min()
max_value = array_20x20.max()

14. Find mean value of a randomly generated array of size 50 

In [67]:
random_array = np.random.rand(50)
mean_value = random_array.mean()

15. Create an array of size 10X10 with 10 element valued as nan 

In [68]:
array_with_nan = np.random.rand(10, 10)
array_with_nan.flat[:10] = np.nan

Pandas practice problems

1. Create a pandas Series using lists and dictionaries? 

In [69]:
import pandas as pd
series_from_list = pd.Series([10, 20, 30, 40])
series_from_dict = pd.Series({'a': 10, 'b': 20, 'c': 30, 'd': 40})
print(series_from_list)
print(series_from_dict)


0    10
1    20
2    30
3    40
dtype: int64
a    10
b    20
c    30
d    40
dtype: int64


2. Create series using NumPy functions in Pandas?  

In [70]:
series_from_numpy = pd.Series(np.linspace(0, 1, 5))
print(series_from_numpy)

0    0.00
1    0.25
2    0.50
3    0.75
4    1.00
dtype: float64


3. Find index and values of series in Pandas?  

In [71]:
sample_series = pd.Series([10, 20, 30, 40], index=['a', 'b', 'c', 'd'])
series_index = sample_series.index
series_values = sample_series.values
print(series_index)
print(series_values)

Index(['a', 'b', 'c', 'd'], dtype='object')
[10 20 30 40]


4. How to specify an index while creating Series in Pandas? Find Length Size and Shape of a 
Series in Pandas?  

In [72]:
indexed_series = pd.Series([100, 200, 300], index=['x', 'y', 'z'])
series_length = len(indexed_series)
series_size = indexed_series.size
series_shape = indexed_series.shape
print(series_length)
print(series_size)
print(series_shape)

3
3
(3,)


5. Find the first or last few rows from a Series in Pandas? 

In [73]:
series = pd.Series(range(1, 11))
first_rows = series.head(3)  # First 3 rows
last_rows = series.tail(3)   # Last 3 rows
print("first three rows:")
print(first_rows)
print("last three rows:")
print(last_rows)

first three rows:
0    1
1    2
2    3
dtype: int64
last three rows:
7     8
8     9
9    10
dtype: int64


6. Checking the duplicate rows and columns using pandas. 

In [74]:
data = pd.DataFrame({
    'A': [1, 2, 2, 4],
    'B': [5, 6, 6, 8],
    'C': [1, 2, 2, 4]
})

duplicate_rows = data.duplicated()
duplicate_columns = data.T.duplicated()
print(duplicate_rows)
print(duplicate_columns)

0    False
1    False
2     True
3    False
dtype: bool
A    False
B    False
C     True
dtype: bool


7. Demonstrate possible missing value analysis approaches using any real world data  

In [75]:
data = pd.DataFrame({
    'Name': ['Alice', 'Bob', 'Charlie', None],
    'Age': [25, None, 30, 28],
    'Salary': [50000, 55000, None, 52000]
})
print("Original data:")
print(data)
missing_summary = data.isnull().sum()   # Check for missing values

filled_data = data.fillna(0)    # Filling missing values with a default value

dropped_data = data.dropna()    # Dropping rows with missing values

data['Age'] = data['Age'].fillna(data['Age'].mean())    # Filling missing values with the mean
print("Data after analysis:")
print(data)


Original data:
      Name   Age   Salary
0    Alice  25.0  50000.0
1      Bob   NaN  55000.0
2  Charlie  30.0      NaN
3     None  28.0  52000.0
Data after analysis:
      Name        Age   Salary
0    Alice  25.000000  50000.0
1      Bob  27.666667  55000.0
2  Charlie  30.000000      NaN
3     None  28.000000  52000.0


8. Suppose you have height and weight data for a group of people. For example: Heights are in 
feet, like 6.5, and weight is in grams, like 80000. In many machine learning situations, you 
want to normalize the data — scale the data so that the values in different columns have 
roughly the same magnitude so that large values (like the weight) don’t overwhelm smaller 
values (like the heights).  
Create a raw data of minimum 40 records of height and weight in above mentioned format 
and use MinMax Normalization to normalize the weights in the range from (-10.0 to 10) as 
well as use Z-score to normalize the weights. 

In [76]:
np.random.seed(0)
heights = np.random.uniform(5.0, 7.0, 40)  # Heights in feet
weights = np.random.uniform(60000, 100000, 40)  # Weights in grams

data = pd.DataFrame({'Height': heights, 'Weight': weights})

In [77]:
min_val = -10.0
max_val = 10.0
data['Weight_MinMax'] = (data['Weight'] - data['Weight'].min()) / (data['Weight'].max() - data['Weight'].min()) * (max_val - min_val) + min_val


In [78]:
data['Weight_ZScore'] = (data['Weight'] - data['Weight'].mean()) / data['Weight'].std()
print("Normalized data:")
print(data)

Normalized data:
      Height        Weight  Weight_MinMax  Weight_ZScore
0   6.097627  74380.316023      -3.250636      -0.151307
1   6.430379  77481.278152      -1.617151       0.121353
2   6.205527  87905.247837       3.873853       1.037909
3   6.089766  62409.018865      -9.556722      -1.203916
4   5.847310  86670.668618       3.223518       0.929355
5   6.291788  86825.514785       3.305086       0.942971
6   5.875174  68415.302443      -6.392809      -0.675797
7   6.783546  65157.051906      -8.109148      -0.962288
8   6.927326  72617.134037      -4.179422      -0.306340
9   5.766883  74548.430838      -3.162079      -0.136525
10  6.583450  82807.870817       1.188723       0.589708
11  6.057790  77544.060538      -1.584079       0.126873
12  6.136089  99534.953522      10.000000       2.060483
13  6.851193  64081.792430      -8.675560      -1.056833
14  5.142072  68355.070244      -6.424537      -0.681094
15  5.174259  66452.380715      -7.426812      -0.848393
16  5.040437  